package PotLuck;

import java.util.ArrayList;
import java.util.Arrays;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import PotLuck.User;
import PotLuck.UserRepository;
import antlr.collections.List;


@Controller    // This means that this class is a Controller
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	@RequestMapping(value ="/index", method= RequestMethod.GET)
	   public String registerForm(Model model) {
		 model.addAttribute(new User());
				return "index";
	    }

	@RequestMapping(value ="/index", method= RequestMethod.POST)
	   public String saveRegister(@ModelAttribute User user ,Model xmodel) {
		userRepository.save(user);
		Iterable<User> u = userRepository.findAll();
		xmodel.addAttribute("list", u);
			return "result";
		}
			
	@RequestMapping(value ="/delete")
	   public  String getForm(Model model ) {
			model.addAttribute("user", new User());
			return "delete";
	    }
	@RequestMapping(value ="/delete" , method= RequestMethod.POST)
	   public @ResponseBody String deleteUser(@ModelAttribute User user ) {
		Integer id= user.getId();
			userRepository.delete(id);
			return "Your Info is Deleted";
	    }
		 		
	

	}
	
	
	












